### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by smarek** [trezor/trezor-android#1]
Can you please publish both snapshots and releases on Maven repository?
Either create Maven repository in branch here on Github or publish into Maven Central.

**Comment by ligi** [comment]
would @jitpack also be an option for you? I will also likely consume this app very soon (with http://walleth.org) - and will use jitpack for this http://jitpack.io - perhaps this is also an option for the trezor-team as this is way less hassle than uploading to maven-center or jitpack ..

**Comment by prusnak** [comment]
jitpack looks nice, +1 for jitpack

**Comment by ligi** [comment]
I am now already consuming the library via jitpack - when https://github.com/trezor/trezor-android/pull/19 is merged and a tag is set I will add how to do this to the README

**Comment by prusnak** [comment]
https://github.com/trezor/trezor-android/pull/19 merged
