### ISSUE TITLE
TREZOR Manager steals the session from Mycelium?

### ISSUE THREAD

**Issue by peca23** [trezor/trezor-android#10]
I can't use Mycelium with TREZOR since I installed TREZOR Manager app.

When I connect TREZOR to my phone, TREZOR Manager asks: "Open TREZOR Manager when this USB device is connected?". If I press OK, it opens the manager app. If I press Cancel, nothing happens.

In any case, when I run Mycelium, it doesn't ask me if I want to use the USB device in Mycelium and I can't force Mycelium to "search" for it in any way.

**Comment by ligi** [comment]
Do you still have this issue? I have both installed and it seems to work as expected.

**Comment by peca23** [comment]
It works for me as well now, however I'm not able to say if it has been fixed or if it has been solved by buying a different phone.

**Comment by ligi** [comment]
Thanks for the info. Do you still have the old phone?

**Comment by peca23** [comment]
I hope so:) I will try to find it at home and test it again, will update later

**Comment by ligi** [comment]
Thanks!

**Comment by prusnak** [comment]
No reply from the OP. Closing, reopen if needed
