### ISSUE TITLE
Set u2f counter after recovery

### ISSUE THREAD

**Issue by karelbilek** [trezor/trezor-android#11]
Set U2F counter after recovery.

This is how I do it in mytrezor in beta

``` javascript
setU2FCounter(session: TrezorJsSession): Promise<any> {
    if (this.supports('u2f')) {
        const timestamp: number = Math.floor(Date.now() / 1000);
        return session.setU2FCounter(timestamp);
    } else {
        return Promise.resolve();
    }                                                                                                          
}
```

`setU2FCounter` calls the message `SetU2FCounter`.

**Comment by runn1ng** [comment]
This is called right after recovery.

This needs to be done so U2F is usable on more devices with for example Google, that checks login counts.

**Comment by prusnak** [comment]
Trezor Manager is not mantained anymore. Please use https://suite.trezor.io/web which works on Android too. Closing the issue.
