### ISSUE TITLE
Add to FDroid

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-android#15]
can be assigned to me - will make the PR for FDroid

**Comment by prusnak** [comment]
Ack!

**Comment by ligi** [comment]
MR is pending: https://gitlab.com/fdroid/fdroiddata/merge_requests/2307

**Comment by ligi** [comment]
MR is merged

**Comment by prusnak** [comment]
What happens next? Do we need to push builds somewhere or this happens automatically? What about the updates? Is it enough just to send another MR with updated tag?

**Comment by ligi** [comment]
It should be build by them in the next cycle (should be soonish). Also updates should happen automagically - but we should have an eye on that as this sometimes breaks - depending on the changes done to the app. So Ideally after doing an update to the app check a week after (to be safe) if the update is also on FDroid and if not: check why. But usually no further MR is needed.

**Comment by prusnak** [comment]
That is great! Woohoo!

**Comment by rfree-d** [comment]
@prusnak hi, F-droid tells me that the signing key of the application changed (when I want to update).
I assume this is normal, you did changed some signing key, right?
Better be paranoid then sorry :)

Can you documented here the this change occured, so it's easily seen by anyone looking at github.com changelog to know this is expected?

Would it be possible to include fingerprint of that signing key in this repository here, so desktop users can download it here and compare with f-droid? I'm not sure, is this possible, how this works, @ligi ? Can you view this signing-key from inside of Android phone, before installing somehow? Thanks

**Comment by ligi** [comment]
FDroid signs with their signing key - not with the one from satoshilabs. I think this is where the confusion comes from - you might have installed 1.0.3 from play and want to update 1.0.5 from fdroid. 
For now you will have to stick to one source - then you will get no warning.
In the future we might be able to use reproducible builds - but this is not yet ready for production (checking https://verification.f-droid.org/ regularly to see if the current version of the trezor app is able to build in a reproducible way)
