### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-android#18]
Just realized there is no licence here  - this blocks #15 and https://github.com/walleth/walleth/issues/15
I would suggest MIT here

**Comment by prusnak** [comment]
Added LGPLv3 in https://github.com/trezor/trezor-android/commit/2040f646a91b120d5df4d815fcef1d8597855373

I think this is more suitable at the moment. (python-trezor also uses the same license)

**Comment by ligi** [comment]
Thanks! LGPLv3 is fine with me as WALLETH is GPL ;-)
