### ISSUE TITLE
Add some Ethereum logos for homescreen

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-android#23]
Currently you have a lot of Options for using the Bitcoin-Logo on the HomeScreen. 
I would like to see some options with the Ethereum logo here - as I rarely use Bitcoin lately and will use the TREZOR mainly in the Ethereum context ;-)
I think at some point there will be more users using TREZOR in combination with Ethereum than with Bitcoin..

**Comment by prusnak** [comment]
@runn1ng is working on adding new set of homescreen images to our webwallet. I will add them to our Android app as well, once we agree on which ones to add. (Ethereum logo WILL be included).

**Comment by runn1ng** [comment]
They are already in beta wallet :)

----
Karel Bílek
kb@karelbilek.com
+420 732 744 940

**Comment by ligi** [comment]
nice!

**Comment by prusnak** [comment]
Added new icons from Karel in https://github.com/trezor/trezor-android/commit/9ea0379f4196a46f2446fbcf71d5663c53982677

It also includes Ethereum icon, so I am closing this issue.
