### ISSUE TITLE
Does not work with TREZOR 1 anymore

### ISSUE THREAD

**Issue by ligi** [trezor/trezor-android#41]
While investigating https://github.com/walleth/walleth/issues/255 - I noticed that even the stock TREZOR manager does not work with TREZOR 1 anymore - Model T works

PS: I do not run the latest firmware 1.6.1 on the TREZOR one - perhaps this is part of the problem - but I also currently do not want to update in case this has anything to do with the errors

**Comment by prusnak** [comment]
Closing as per https://github.com/walleth/walleth/issues/255#issuecomment-396615836
