### ISSUE TITLE
TREZOR in all caps everywhere in Trezor Manager App

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-android#55]
Trezor Manager App for Android still has "TREZOR" in the name of the app and also everywhere in the app: "Complete the action on TREZOR device", "Connect your TREZOR" etc.

![2019-09-13 17 14 08](https://user-images.githubusercontent.com/31442634/64873692-ef76ae80-d649-11e9-975e-1048dacbd1fe.jpg)
![2019-09-13 17 06 24](https://user-images.githubusercontent.com/31442634/64873315-12ed2980-d649-11e9-8e9c-adb5250ae367.jpg)

**Comment by prusnak** [comment]
Fixed in 6d5e563af5eae7d617ecad35f811823e490596a3
