### ISSUE TITLE
Text in pop-ups is unreadable, black-on-black issue

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-android#56]
Tested on VisionBook 10Qa 3G Tablet. 

![2019-09-13 17 17 23](https://user-images.githubusercontent.com/31442634/64873959-73c93180-d64a-11e9-9d84-61b0e04bba49.jpg)
![2019-09-13 17 17 10](https://user-images.githubusercontent.com/31442634/64873961-7461c800-d64a-11e9-9fc3-9215fe31cbaa.jpg)
![2019-09-13 17 17 17](https://user-images.githubusercontent.com/31442634/64873962-7461c800-d64a-11e9-8590-591ec73d9751.jpg)
![2019-09-13 17 17 29](https://user-images.githubusercontent.com/31442634/64873964-7461c800-d64a-11e9-96c0-cd055fe7afe3.jpg)

**Comment by prusnak** [comment]
Trezor Manager is not mantained anymore. Please use https://suite.trezor.io/web which works on Android too. Closing the issue.
