### ISSUE TITLE
Wrong firmware header when trying to install firmware onto Trezor One

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-android#57]
It happens only with Trezor One, no issues with Trezor T. 

Steps to reproduce:
1) Plug in the device with no firmware installed
2) Click on INSTALL FIRMWARE in the app
3) It seems like the installation process is starting - "Preparing" is displayed on device
4) The process results with a "Wrong firmware header" error

![2019-09-13 17 43 18](https://user-images.githubusercontent.com/31442634/64875924-58602580-d64e-11e9-86cb-09b7c3279730.jpg)

**Comment by brianddk** [comment]
This problem persists with the old version (2.0.10) and the latest version (v2.1.8) of Trezor Manager for Android.  Since Trezor One transitioned to the `TREZOR_ONE_V2` firmware format, was that change picked up in this utility?

**Comment by dudhatparesh** [comment]
The issue for the Trezor-One device still present.
If I try to install 1.8.3 it says wrong firmware header. and If I try to install 2.1.8 it says Firmware is too big.
I am developing a custom app to manage all functionality of trezor based on this repository so I can't tell the user to go to the Trezor website and install the firmware. can we have a solution for either of this firmware?

**Comment by dudhatparesh** [comment]
or can we have a version that works without the wrong firmware header error? I tried up to 1.8.1 but its also giving the same error

**Comment by prusnak** [comment]
Update the device using the web wallet first.

**Comment by prusnak** [comment]
Trezor Manager is not mantained anymore. Please use https://suite.trezor.io/web which works on Android too. Closing the issue.
