### ISSUE TITLE
No warning in the app if the device with backup failed connected

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-android#58]
Trezor One, Trezor T

Steps to reproduce: 
1. Connect a device with backup failed warning 

Result: there is no warning or instruction in the Trezor Manager. 
![photo_2019-09-18_12-12-45](https://user-images.githubusercontent.com/31442634/65139963-cd947780-da0d-11e9-9306-3ae312e276f1.jpg)

**Comment by Honestbui** [comment]
I looked at the Trezor and saw at the top of the screen 'BACKUP FAILED!'.I searched on the User Manual and Support sections and found nothing for that error.pleased help me

**Comment by prusnak** [comment]
@Honestbui see https://wiki.trezor.io/Recovery_seed_backup_fail

Trezor Manager is not mantained anymore. Please use https://suite.trezor.io which works on Android too. Closing the issue.
