### ISSUE TITLE
option to create wallet with 256 bits master key, and SLIP39

### ISSUE THREAD

**Issue by Furunodo** [trezor/trezor-android#61]
It seems with Trezor Manager I can only create a wallet with just 12 words, so 128 bits master key.
Not adequate for a long term HODL.

Ideally I want to be able to choose the master key size myself (between 128 and 256), and I'd also want to be able to create a SLIP39 setup from the Android app.

**Comment by prusnak** [comment]
Trezor Manager is not mantained anymore. Please use https://suite.trezor.io/web which works on Android too. Closing the issue.
