### ISSUE TITLE
App gets into inconsistent state

### ISSUE THREAD

**Issue by karelbilek** [trezor/trezor-android#8]
App gets into inconsistent state with these steps:
1. start app, connect device
2. turn passphrase on (or off, if it's on)
3. disconnect the device
4. the device is still showing up as connected, even when it's connected
5. clicking on any action shows up "loading" animation, which never stops

Interestingly, there is no way to stop this animation. Even when I uninstall and re-install the app (!!!), the loading is still showing. The only way to stop it is to reboot the phone.

Similar way to get to the same state (doesn't work 100% always) is:
1. start app, connect device
2. exit from the app by tapping "home" button
3. disconnect device (without the app on screen)
4. go back to the app, the device is showing as connected
5. clicking on any action shows up "loading" animation, which never stops

My phone is Lenovo P70. I couldn't reproduce the bug on a different Samsung phone. But the first sequence of steps always reproduces the error on my Lenovo.

Trezor is working fine with MyCelium on the same phone, but I haven't tested it as thoroughly as this app.

**Comment by Deikras25** [comment]
⁰¹

**Comment by karel-3d** [comment]
the app is no longer supported, is it? Should I close this?

**Comment by prusnak** [comment]
No, please keep it open.

**Comment by karel-3d** [comment]
ok then. But I won't confirm/deny the solution anymore as I don't get the original phone and am using iOS now :D

**Comment by prusnak** [comment]
Trezor Manager is not mantained anymore. Please use https://suite.trezor.io/web which works on Android too. Closing the issue.
